name: root
channels:
    # terradue must be first and then defaults, otherwise there will be package
    # inconsistency errors
    - terradue
    - defaults
    - conda-forge
    #- conda-forge/label/broken
dependencies:
    - java-1.7.0-openjdk-cos6-x86_64=1.7.0.131
    - jpy=0.9.0
    - snap=8.0.0=py37_2
    - python=$py_ver
    # - ipython
    # - ipykernel
    # - conda-forge::blas=*=openblas
    # - bokeh=2.3
    # - cython=0.29
    # - dask=2021.4
    # - h5py=3.2
    # - matplotlib-base=3.4
    # - pandas=1.2
    # - scikit-image=0.18
    # - scikit-learn=0.24
    # - scipy=1.6
    # - seaborn=0.11
    # - statsmodels=0.12
