channels:
    - terradue
    - defaults
    - conda-forge
    - conda-forge/label/broken
dependencies:
    - python=3.8
    - pip=21.0.1
    - ipython=7.23.0
    - ipykernel=5.5.3
    - java-1.7.0-openjdk-cos6-x86_64=1.7.0.131
    - jpy=0.9.0
    - snap=8.0.0=py38_2
    - conda-forge::blas=*=openblas
    - bokeh=2.3
    - cython=0.29
    - dask=2021.4
    - h5py=3.2
    - matplotlib-base=3.4
    - pandas=1.2
    - scikit-image=0.18
    - scikit-learn=0.24
    - scipy=1.6
    - seaborn=0.11
    - statsmodels=0.12
    - pip:
          - -r requirements.txt
